services:
  # MongoDB
  cadmus-febo-mongo:
    image: mongo
    container_name: cadmus-febo-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null
    ports:
      - 27017:27017
    networks:
      - cadmus-febo-network

 # PostgreSQL
  cadmus-febo-pgsql:
    image: postgres
    container_name: cadmus-febo-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-febo-network

  # Cadmus febo API
  cadmus-febo-api:
    image: vedph2020/cadmus-febo-api:1.0.1
    container_name: cadmus-febo-api
    ports:
      - 5105:8080
    depends_on:
      - cadmus-febo-mongo
      - cadmus-febo-pgsql
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-febo-mongo:27017/{0}
      - CONNECTIONSTRINGS__AUTH=Server=cadmus-febo-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-febo-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-febo-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
      - SEED__DELAY=20
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
    networks:
      - cadmus-febo-network

  # Cadmus febo App
  cadmus-app:
    image: vedph2020/cadmus-febo-app:1.0.1
    container_name: cadmus-febo-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-febo-api
    networks:
      - cadmus-febo-network

networks:
  cadmus-febo-network:
    driver: bridge
